### ISSUE TITLE
Better support for split payments? 

### ISSUE THREAD

**Issue by johngribbin** [clams-tech/Remote#151]
I tried to pay a $35 invoice and something very odd happened. Firstly, the payment stayed in a pending state, but for a much smaller amount: 

![2a5a2d903815d68afc2c531aae45a0d662fae11d36bec49ef254fd86f7d01dd0](https://user-images.githubusercontent.com/30157175/230731015-3ccc503e-0981-4fa7-a967-d9789e4f87b1.jpg)

Payment was pending for a few minutes so I tried refreshing, but was still the same state. After about 40 minutes, I checked the app again, refreshed and saw that it failed: 

![748e1e6c43fe4d44c75e4b5d34c0a5b3afd472c15662cbda5046111c92c5d0e5](https://user-images.githubusercontent.com/30157175/230731047-43c78bf6-c743-4104-816d-04108cac3021.jpg)

**Comment by aaronbarnardsound** [comment]
Fixed in V2
