### ISSUE TITLE
Nodes with large number of payments get rate limited

### ISSUE THREAD

**Issue by johngribbin** [clams-tech/Remote#159]
App throws rate limit error on first load (Rune recipe has rate limit of 60): 
![image](https://user-images.githubusercontent.com/30157175/236637352-33f54881-3578-4128-9388-8aec38319390.png)

App only loads payments up until March 2021:
![image](https://user-images.githubusercontent.com/30157175/236637361-ec224328-8782-4abe-b016-a0e5d7c03c4e.png)

More details: 
- Node is 2 years old with significant number of payments.
- Node is running clboss - so there are a decent number of rebalances. 
- Screen loads up with notifications of payments, right before the rate limited notification appears
- Node is running on Tor and connection is made via alby proxy

**Comment by farscapian** [comment]
I get a similar bug when looking at the /channels route on a node with a lot of channels. Assuming Clams is exceeding the rune rate limit on fetching channels details.
