### ISSUE TITLE
Bug: Inconsistent QR scanning ability after saving to file. 

### ISSUE THREAD

**Issue by farscapian** [clams-tech/Remote#183]
In all cases (BOLT12, BOLT11, Node Connect, and Node Pubkey) where QR codes are shown, my phone QR scanner works fine when the QR code is in the browser. However, when saving that QR to a file using the little save button on the lower right of the QR, then opening the resulting .png file, the QR code DOES NOT scan at all. Wondering if there's some bug here.

**Comment by aaronbarnardsound** [comment]
I was able to scan saved and copied QR's but the export does not have any whitespace on the edges which may be making it harder to scan.  #184 adds some padding around the QR which should help with making it easier to scan.

**Comment by aaronbarnardsound** [comment]
@farscapian this has been merged in to production, so let me know if it fixes it on your end.
