### ISSUE TITLE
Connecting to a Tor node?

### ISSUE THREAD

**Issue by IngwiePhoenix** [clams-tech/Remote#191]
My CLN node runs primarily in Tor and I would like to not just have my phone to look at my current node's information and manage it.

So is there a way I could make the app reach it?

Thanks!

**Comment by aaronbarnardsound** [comment]
Hey @IngwiePhoenix we need to add TOR support to our WebSocket proxy which we plan on doing soon. In the meantime you could try using the alby proxy (`wss://lnproxy.getalby.com`) which supports TOR in the advanced connection options:

<img width="653" alt="Screenshot 2023-08-16 at 9 04 42 am" src="https://github.com/clams-tech/App/assets/29873495/bfa92e3d-10c6-4415-86fc-7585fae8da93">

**Comment by IngwiePhoenix** [comment]
Oh neat! Can I also host my own proxy, by chance? Might come in handy.

**Comment by IngwiePhoenix** [comment]
I tried the Alby proxy and that did not work either.

I run Core Lightning; maybe this is only compatible with LND? Or is there a plugin I need to have for this to work?

**Comment by aaronbarnardsound** [comment]
This is definitely for Core Lightning. Is your node reachable at the address that you are entering? Maybe the get Alby proxy is no longer working with TOR. We have had other users successfully connect via that proxy though.

You could try connecting on our [staging site](https://staging.app.clams.tech) and look at the console logs to get a better idea of why it cannot connect.

Yes you can run your own proxy server!

[Alby fork that allows TOR](https://github.com/getAlby/lnsocket-proxy)
[What we run (no TOR)](https://github.com/clams-tech/ln-ws-proxy)

**Comment by aaronbarnardsound** [comment]
We are going to prioritise adding support for TOR connections to our WS proxy early this year.

**Comment by johngribbin** [comment]
the getalby proxy is available as an option now- and it works well with Tor. So i am closing this issue.
