### ISSUE TITLE
Enhancement: Change input widget for the Quantity field when paying a BOLT12 Offer.

### ISSUE THREAD

**Issue by farscapian** [clams-tech/Remote#199]
I'm working on a project that requires high integer quantities when paying BOLT12 offers. The current input widget is a step-wise up/down thing. Would be better from a developer point of view to just type in the number I want to test against, especially near the min/max values.
![image](https://github.com/clams-tech/App/assets/23437177/8f67bed0-e653-41bd-82a2-eeef52e927cb)

**Comment by aaronbarnardsound** [comment]
Going to get a start on this one today.

**Comment by aaronbarnardsound** [comment]
Oh wait this is from V1. Going to close this for now since we aren't actively developing v1 at this time.
