### ISSUE TITLE
EmbassyOS Support

### ISSUE THREAD

**Issue by cryptoquick** [clams-tech/Remote#221]
It'd be really cool if Clams could be used on EmbassyOS/StartOS... I think this requires some packaging.

Now that Spark Wallet no longer works on StartOS, Clams could be a viable replacement, and it could have a bit of a moment.

**Comment by aaronbarnardsound** [comment]
Yeah great suggestion. We'll look in to what is involved to package it up for the node projects and post an update here.

**Comment by k0gen** [comment]
@cryptoquick, thank you for opening this issue/suggestion. I’ve recently discovered Clams and I really like it!

@aaronbarnardsound, check out the [Developer Docs](https://docs.start9.com/latest/developer-docs/) which contain all the necessary information for packaging a service for StartOS. In a nutshell, the steps are:
- Set up your StartOS testing dev box. This can be a physical machine or a VM. If you’re using a Mac, here’s a [quick guide](https://blog.start9.com/running-startos-on-apple-silicon/) I wrote specifically for that.
- Use [hello-world-startos](https://github.com/start9labs/hello-world-startos) as your service template.
- Build it to get familiar with the process.

Don’t hesitate to reach out if you need any help or assistance. 
Let’s make this fantastic software accessible to all sovereign node runners using StartOS!

**Comment by farscapian** [comment]
I will work on this issue. Standing up a start9 VM today.

**Comment by aaronbarnardsound** [comment]
@farscapian you are an absolute legend. Thanks for taking this on. Let me know if you need any assistance as well.

**Comment by k0gen** [comment]
@farscapian , I hope you're doing well. Just checking in to see how the progress is going with the Clams packaging for StartOS?

As a reference, you might find it useful to visit the [commit history](https://github.com/PrimalHQ/primal-startos/commits/master/) of the Primal project. It's a great example of going from a hello-world template to a working service for StartOS.

Also, remember that you can always reach out in our matrix room [#community-dev](https://matrix.to/#/%23community-dev:matrix.start9labs.com) for any assistance or discussions.

**Comment by farscapian** [comment]
Hey sorry about that. Unfortunately this project is  competing with my other projects, so I may be a tad slow on implementing this. 

My embassy is all synced and I've started going through the documents and creating the required repos. I should have an update in a week hopefully. I already have a working dockerfile, just gotta get everything wired up correctly I think.

**Comment by aaronbarnardsound** [comment]
@farscapian I think whatever is simplest to start off with would be my preference, so probably serving static output from nginx. We can see how that goes and take feedback from there I reckon.

**Comment by farscapian** [comment]
Just posting an update on this one. I have [a pull request](https://github.com/Start9Labs/cln-startos/pull/126) on Start9 to update CLN to enable the websocket interface as a torv3 onion endpoint. This would enable any Clams Remote PWA running in Tor Browser to directly connect to their CLN node via native (i.e., not CLNRest) websocket, assuming they have the service onion endpoint.

This [clams-startos](https://github.com/farscapian/clams-startos) repo works in conjunction with the above pull request. clams-startos is a simple web server that serves Clams Remote static build output. The node-based server process performance was not sufficient for Tor Browser, so i went with static build output instead which has significantly better performance in Tor Browser. This means that we don't get URL handling, but I'm hoping we can get that functionality back by implementing [query parameter reflection](https://github.com/clams-tech/Remote/issues/246).

**Comment by johngribbin** [comment]
Remote is now in the community registry. Cheers to @farscapian for leading the efforts on this one!! 

<img width="1321" alt="Screenshot 2024-05-23 at 9 12 59 PM" src="https://github.com/clams-tech/Remote/assets/30157175/a699ff10-a743-4fb1-9c3c-ee6b01479360">
