### ISSUE TITLE
Enhancement: Add ability to receive via private channel  

### ISSUE THREAD

**Issue by johngribbin** [clams-tech/Remote#243]
User request: 

> Hey guys. I have a single private channel opened with my other node and can send fine, but in order to receive I need to include routing hints as part of the invoice. Is it possible to add the feature similar to how RTL and Zeus have?

![image](https://github.com/clams-tech/Remote/assets/30157175/7d46bc0f-1964-41e3-a509-58f1c5bd4f88)
![image](https://github.com/clams-tech/Remote/assets/30157175/86f7aca3-3778-4126-9470-06765e2ab5b3)

From CLN docs, there is a `exposeprivatechannels` flag that we could have a toggle for:

> If specified, exposeprivatechannels overrides the default route hint
logic, which will use unpublished channels only if there are no
published channels. If true unpublished channels are always considered
as a route hint candidate; if false, never. If it is a short channel id
(e.g. 1x1x3) or array of short channel ids (or a remote alias), only those specific channels
will be considered candidates, even if they are public or dead-ends.

**Comment by johngribbin** [comment]
ill take a look at this one

**Comment by johngribbin** [comment]
![Uploading Screenshot 2024-05-27 at 8.22.26 PM.png…]()

@aaronbarnardsound Perhaps we only show the `Expose private channels` toggle if there are private channels in their active channels list?

**Comment by aaronbarnardsound** [comment]
We could do that, but it would require a larger change since we do not store that state in the db currently. I would recommend always having the toggle there for now and default to off.
