### ISSUE TITLE
Feature Request: Single Wallet mode

### ISSUE THREAD

**Issue by farscapian** [clams-tech/Remote#244]
Single Wallet mode (could be rolled into LARP mode) would indicate to Clams that ONE and ONLY ONE wallet can be used at a time. When specified, any new QR code the user scans will completely replace any existing single-mode wallet. When enabled, the Wallets button DOES NOT appear and the user interface reverts to a Clams v1 simplified interface with Balance up-front. "Input" button becomes "Send". Invoices issued under the "Receive" button advance to single-use BOLT12 offers instead of BOLT11 (for easier scanning).

If any existing multi-wallet (standard) Clams Remote instance resides in the browser cache, Clams will ask the user to 1) use a different browser or 2) direct the user to delete existing wallets before instantiating a Single Wallet mode instance.

**Comment by johngribbin** [comment]
@farscapian I'll take a look at this.

**Comment by johngribbin** [comment]
@farscapian `any new QR code the user scans will completely replace any existing single-mode wallet.`

^ This is now on dev. 

As for the rest of your issue - I will taking a look at all of the feedback from Austin Design Club thingy - I should be able to cover the rest of your requests on this issue as a lot of their feedback was similar.

**Comment by farscapian** [comment]
This feature is working great! The original motivation for this functionality was from the Lightning LARP to improve user experience. However, an unexpected side effect is that it simplifies roygbiv.guide/demo.
