### ISSUE TITLE
BUG: Valid P2PKH Addresses Not Validating Correctly

### ISSUE THREAD

**Issue by lnbc1QWFyb24** [clams-tech/Remote#251]
When entering a valid P2PKH address to send onchain funds, the client side validation is indicating it is not a valid address, making it impossible to send funds to those address types.

I did some digging in to it and has something to do with an invalid `Buffer` version that we are injecting in to the build. Will have to spend some more time trying to fix it, or look in to an alternative way to validate addresses.

**Comment by johngribbin** [comment]
This issue is resolved in the latest release
